name: run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          pip install pyinstaller pygame
          pyinstaller --onefile --add-data "res:res" main.py
      - uses: actions/upload-artifact@v4
        with:
          name: macOS-Game-Executable
          path: dist/main
