name: run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies and Build
        run: |
          pip install pyinstaller pygame
          pyinstaller --onefile --name "run" --collect-all pygame main.py
          
      - name: Ad-hoc Code Sign Binary
        run: |
          codesign --force --deep --sign - "dist/run"
          
      - name: Stage Assets Outside Executable
        run: |
          cp -R res dist/
          
      - name: Upload Standalone Game and Assets
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Game-Bundle
          path: |
            dist/run
            dist/res/
