name: run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          pip install pyinstaller pygame
          pyinstaller --onedir --name "run" main.py
          
      - name: Ad-hoc Code Sign Binary
        run: |
          codesign --force --deep --sign - "dist/run/run.app"
          
      - uses: actions/upload-artifact@v4
        with:
          name: macOS-Game-Folder
          path: "dist/run/"
